In [1]:
import numpy as np
from recstate import G_matrix

In [2]:
gamma = 4+1j
phi = 0.3
zeta = 0.2+2j
cutoff = 5

In [3]:
G_matrix(gamma, phi, zeta, cutoff)

array([[-3.85211928e-05-1.06939857e-04j,  3.53656445e-05+1.18200402e-04j,
        -9.73169272e-05-7.31882292e-05j,  1.53787533e-04+3.06952108e-05j,
        -1.51354890e-04+5.35945465e-05j],
       [ 4.03135550e-04-5.07093585e-04j, -4.68554570e-04+4.95629782e-04j,
         6.29478204e-05-6.45147774e-04j,  2.79277405e-04+7.92613815e-04j,
        -6.40636738e-04-5.33972641e-04j],
       [ 2.51581427e-03+2.96206512e-04j, -2.50977151e-03-6.07207697e-04j,
         2.11318428e-03-1.02810319e-03j, -1.97644053e-03+2.36153769e-03j,
         4.68556714e-04-2.90662807e-03j],
       [ 3.32334497e-03+7.08474737e-03j, -2.12292426e-03-7.40876218e-03j,
         5.63355453e-03+3.56629205e-03j, -8.76400402e-03-1.43662266e-03j,
         7.54983378e-03-2.96560317e-03j],
       [-1.09732047e-02+1.69418389e-02j,  1.34732924e-02-1.36257633e-02j,
        -8.55281339e-05+1.56032200e-02j, -7.71675888e-03-1.98468440e-02j,
         1.44612926e-02+1.13103944e-02j]])

In [4]:
from thewalrus.fock_gradients import Dgate,Sgate,Rgate,Kgate,BSgate


In [5]:
gate_d = Dgate(np.abs(gamma), np.angle(gamma),cutoff+100)[0]
gate_r = Rgate(phi,cutoff+100)[0]
gate_s = Sgate(np.abs(zeta), np.angle(zeta),cutoff+100)[0]

In [6]:
(gate_d@gate_r@gate_s)[:cutoff,:cutoff]

array([[-3.85211928e-05-1.06939857e-04j,  3.53656445e-05+1.18200402e-04j,
        -9.73169272e-05-7.31882292e-05j,  1.53787533e-04+3.06952108e-05j,
        -1.51354890e-04+5.35945465e-05j],
       [ 4.03135550e-04-5.07093585e-04j, -4.68554570e-04+4.95629782e-04j,
         6.29478204e-05-6.45147774e-04j,  2.79277405e-04+7.92613815e-04j,
        -6.40636738e-04-5.33972641e-04j],
       [ 2.51581427e-03+2.96206512e-04j, -2.50977151e-03-6.07207697e-04j,
         2.11318428e-03-1.02810319e-03j, -1.97644053e-03+2.36153769e-03j,
         4.68556714e-04-2.90662807e-03j],
       [ 3.32334497e-03+7.08474737e-03j, -2.12292426e-03-7.40876218e-03j,
         5.63355453e-03+3.56629205e-03j, -8.76400402e-03-1.43662266e-03j,
         7.54983378e-03-2.96560317e-03j],
       [-1.09732047e-02+1.69418389e-02j,  1.34732924e-02-1.36257633e-02j,
        -8.55281339e-05+1.56032200e-02j, -7.71675888e-03-1.98468440e-02j,
         1.44612926e-02+1.13103944e-02j]])

In [8]:
np.einsum("ab,bc,cd->ad",gate_d,gate_r,gate_s)[:cutoff,:cutoff]

array([[-3.85211928e-05-1.06939857e-04j,  3.53656445e-05+1.18200402e-04j,
        -9.73169272e-05-7.31882292e-05j,  1.53787533e-04+3.06952108e-05j,
        -1.51354890e-04+5.35945465e-05j],
       [ 4.03135550e-04-5.07093585e-04j, -4.68554570e-04+4.95629782e-04j,
         6.29478204e-05-6.45147774e-04j,  2.79277405e-04+7.92613815e-04j,
        -6.40636738e-04-5.33972641e-04j],
       [ 2.51581427e-03+2.96206512e-04j, -2.50977151e-03-6.07207697e-04j,
         2.11318428e-03-1.02810319e-03j, -1.97644053e-03+2.36153769e-03j,
         4.68556714e-04-2.90662807e-03j],
       [ 3.32334497e-03+7.08474737e-03j, -2.12292426e-03-7.40876218e-03j,
         5.63355453e-03+3.56629205e-03j, -8.76400402e-03-1.43662266e-03j,
         7.54983378e-03-2.96560317e-03j],
       [-1.09732047e-02+1.69418389e-02j,  1.34732924e-02-1.36257633e-02j,
        -8.55281339e-05+1.56032200e-02j, -7.71675888e-03-1.98468440e-02j,
         1.44612926e-02+1.13103944e-02j]])