In [1]:
import numpy as np
from recstate2mode import G_matrix,G_matrix2

In [2]:
gamma = np.array([0,0],dtype = np.complex128)
phi = np.array([0,0],dtype = np.complex128)
zeta = np.array([0,0],dtype = np.complex128)
theta = 0
psi = 0
theta1 = np.pi/6
psi1 = np.pi
cutoff_dim = 2
cutoff_plus = 20

In [3]:
G,Sigma,mu,W,V = G_matrix(gamma, phi, theta1, psi1, zeta, theta, psi,cutoff_dim)

In [4]:
Sigma

array([[ 0.       +0.j, -0.       +0.j, -0.8660254-0.j,  0.       +0.j],
       [-0.       +0.j,  0.       +0.j,  0.       +0.j, -0.8660254-0.j],
       [-0.8660254-0.j,  0.       +0.j,  0.       +0.j,  0.       +0.j],
       [ 0.       +0.j, -0.8660254-0.j,  0.       +0.j,  0.       +0.j]])

In [5]:
mu

array([ 0.+0.j,  0.+0.j, -0.-0.j, -0.-0.j])

In [6]:
W

array([[ 0.8660254+0.000000e+00j,  0.5      +6.123234e-17j],
       [-0.5      +6.123234e-17j,  0.8660254+0.000000e+00j]])

In [7]:
V

array([[ 1.+0.j, -0.+0.j],
       [ 0.+0.j,  1.+0.j]])

In [8]:
from thewalrus.fock_gradients import Dgate,Sgate,Rgate,BSgate
# D(gamma)R(phi)BS(theta1,psi1)S(z)BS(theta,psi)

In [9]:
gate_d1 = Dgate(np.abs(gamma[0]), np.angle(gamma[0]),cutoff_dim+cutoff_plus)[0]
gate_d2 = Dgate(np.abs(gamma[1]), np.angle(gamma[1]),cutoff_dim+cutoff_plus)[0]

gate_r1 = Rgate(phi[0],cutoff_dim+cutoff_plus)[0]
gate_r2 = Rgate(phi[1],cutoff_dim+cutoff_plus)[0]

gate_bs1 = BSgate(theta1,psi1,cutoff_dim+cutoff_plus)[0]

gate_s1 = Sgate(np.abs(zeta[0]), np.angle(zeta[0]),cutoff_dim+cutoff_plus)[0]
gate_s2 = Sgate(np.abs(zeta[1]), np.angle(zeta[1]),cutoff_dim+cutoff_plus)[0]

gate_bs2 = BSgate(theta,psi,cutoff_dim+cutoff_plus)[0]

In [10]:
# D(gamma)R(phi)BS(theta1,psi1)S(z)BS(theta,psi)
#G_real = np.einsum("ac,bd,ce,df,egfh,gi,hj,ikjl->akbl",gate_d1,gate_d2,gate_r1,gate_r2,gate_bs1,gate_s1,gate_s2,gate_bs2)

In [11]:
G

array([[[[ 1.       +0.j, -0.       +0.j],
         [ 0.       +0.j,  0.       -0.j]],

        [[ 0.       +0.j,  0.8660254+0.j],
         [ 0.       +0.j,  0.       +0.j]]],


       [[[ 0.       +0.j, -0.       +0.j],
         [ 0.8660254+0.j,  0.       +0.j]],

        [[ 0.       +0.j,  0.       +0.j],
         [ 0.       +0.j,  0.75     +0.j]]]])

In [12]:
np.transpose(gate_bs1[:cutoff_dim,:cutoff_dim,:cutoff_dim,:cutoff_dim],(0,2,1,3))

array([[[[ 1.       +0.000000e+00j,  0.       +0.000000e+00j],
         [ 0.       +0.000000e+00j,  0.       +0.000000e+00j]],

        [[ 0.       +0.000000e+00j,  0.8660254+0.000000e+00j],
         [-0.5      -6.123234e-17j,  0.       +0.000000e+00j]]],


       [[[ 0.       +0.000000e+00j,  0.5      -6.123234e-17j],
         [ 0.8660254+0.000000e+00j,  0.       +0.000000e+00j]],

        [[ 0.       +0.000000e+00j,  0.       +0.000000e+00j],
         [ 0.       +0.000000e+00j,  0.5      +0.000000e+00j]]]])