In [1]:
import numpy as np
from fastgaussian1 import new_state,G_matrix

In [2]:
gamma = np.array([0.1,0],dtype = np.complex128)
phi = np.array([0,0.3],dtype = np.complex128)
zeta = np.array([0.2,0],dtype = np.complex128)
theta1 = 0
psi1 = 0
theta = 0
psi = 0
cutoff_dim = 2
state = np.random.rand(cutoff_dim,cutoff_dim) + 1.0j*np.random.rand(cutoff_dim,cutoff_dim)
old_state = state/ np.linalg.norm(state)

In [3]:
G,S,mu = G_matrix(gamma, phi, theta1, psi1, zeta, theta, psi,cutoff_dim)

In [4]:
from thewalrus.fock_gradients import Dgate,Sgate,Rgate,Kgate,BSgate
# D(gamma)R(phi)BS(theta1,psi1)S(z)BS(theta,psi)

In [5]:
gate_d1 = Dgate(np.abs(gamma[0]), np.angle(gamma[0]),cutoff_dim)
gate_d2 = Dgate(np.abs(gamma[1]), np.angle(gamma[1]),cutoff_dim)
gate_d = np.tensordot(gate_d1[0],gate_d2[0],axes=0)

gate_r1 = Rgate(phi[0],cutoff_dim)
gate_r2 = Rgate(phi[1],cutoff_dim)
gate_r = np.tensordot(gate_r1[0],gate_r2[0],axes=0)

gate_bs1 = BSgate(theta1,psi1,cutoff_dim)[0]

gate_s1 = Sgate(np.abs(zeta[0]), np.angle(zeta[0]),cutoff_dim)
gate_s2 = Sgate(np.abs(zeta[1]), np.angle(zeta[1]),cutoff_dim)
gate_s = np.tensordot(gate_s1[0],gate_s2[0],axes=0)

gate_bs2 = BSgate(theta,psi,cutoff_dim)[0]

In [6]:
gate_d@gate_r@gate_bs1@gate_s@gate_bs2

array([[[[0.98517692+0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.94117546+0.29113969j]],

        [[0.        +0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.        +0.j        ]]],


       [[[0.        +0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.        +0.j        ]],

        [[0.95613856+0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.91343405+0.28255826j]]]])

In [7]:
from thewalrus.fock_gradients import G2gate_jit

In [8]:
G2,S2,mu2 = G2gate_jit(np.array([0,0.3]), np.array([0.1,0]), np.array([0,0]), np.array([0.2,0]), np.array([0,0]), cutoff_dim)

In [9]:
mu

array([ 0.11973753+0.j, -0.0980328 -0.j,  0.        +0.j, -0.        -0.j])

In [10]:
mu2

array([ 0.11973753+0.j, -0.0980328 +0.j,  0.        +0.j,  0.        +0.j])

In [11]:
S

array([[-0.19737532-0.j        ,  0.980328  +0.j        ,
         0.        +0.j        ,  0.        -0.j        ],
       [ 0.980328  +0.j        ,  0.19737532+0.j        ,
         0.        +0.j        , -0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.95533649+0.29552021j],
       [ 0.        -0.j        , -0.        +0.j        ,
         0.95533649+0.29552021j,  0.        +0.j        ]])

In [12]:
S2

array([[-0.19737532-0.j        ,  0.980328  +0.j        ,
        -0.        +0.j        , -0.        +0.j        ],
       [ 0.        +0.j        ,  0.19737532+0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        -0.j        ,  0.95533649+0.29552021j],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ]])

In [13]:
G

array([[[[ 0.98712334+0.j        , -0.        +0.j        ],
         [ 0.        +0.j        , -0.94303495-0.29171489j]],

        [[-0.09677046+0.j        ,  0.        +0.j        ],
         [-0.        +0.j        ,  0.09244836+0.02859763j]]],


       [[[ 0.11819571+0.j        ,  0.        +0.j        ],
         [ 0.        +0.j        , -0.11291668-0.03492922j]],

        [[-0.9792917 +0.j        ,  0.        +0.j        ],
         [ 0.        +0.j        ,  0.9355531 +0.28940049j]]]])

In [14]:
G2

array([[[[ 0.98420516+0.j        ,  0.        +0.j        ],
         [ 0.        +0.j        ,  0.9402471 +0.29085251j]],

        [[-0.09648439+0.j        ,  0.        +0.j        ],
         [ 0.        +0.j        , -0.09217506-0.02851309j]]],


       [[[ 0.1178463 +0.j        ,  0.        +0.j        ],
         [ 0.        +0.j        ,  0.11258287+0.03482596j]],

        [[ 0.95329107+0.j        ,  0.        +0.j        ],
         [ 0.        +0.j        ,  0.91071374+0.28171677j]]]])

In [15]:
gate_d@gate_r@gate_bs1@gate_s@gate_bs2

array([[[[0.98517692+0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.94117546+0.29113969j]],

        [[0.        +0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.        +0.j        ]]],


       [[[0.        +0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.        +0.j        ]],

        [[0.95613856+0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.91343405+0.28255826j]]]])